### ISSUE TITLE
Sugestão: Criar um template básico para os Magi

### ISSUE THREAD

**Issue by Thylaellas** [Boifuba/Ars-Magica#10]
Estou me oferecendo para criar um template básico para futuramente facilitar a criação dos magi em suas respectivas casas. Acho que assim seria possível quantificar explicitamente quão poderoso o personagem está. Vou postar o que já fiz no momento. Pretendo fazer futuramente os templates para magos inicias para cada casa.
[Templates, Vantagens e Desvantagens ARS MAGICA.docx](https://github.com/Boifuba/Ars-Magica/files/6912857/Templates.Vantagens.e.Desvantagens.ARS.MAGICA.docx)

**Comment by Boifuba** [comment]
## Ótimo a iniciativa.

Concord com a template. Acho que podemos colocar ela no gcs já para futuras fichas. 

> *Sobre escolas acho que esse caminho vai bater um problema. Cada casa nos seus livros apresentam novas habilidades. O ideal seria fazer o template de cada casa. Tu teria que ler os 3 livros de linhagens para fazer isso. Eu não pego junto disso com você para não:*

1.  Atropelar seu trabalho
2. Tou com muitas outras coisas para fazer no projeto.

**Comment by Boifuba** [comment]
@Thylaellas  Alguma mudança? vai poder continuar a fazer isso agora?

**Comment by Boifuba** [comment]
abandonado
