### ISSUE TITLE
Edito da Servidão 1

### ISSUE THREAD

**Issue by lincolnkerber** [Boifuba/Ars-Magica#12]
![image](https://user-images.githubusercontent.com/88008361/128648704-04ee5331-de9f-493b-b99c-b66de5b7bedc.png)

1. Todo aldeão deve trabalhar 2 dias por semana nas terras do senhor.
2. Crianças a partir dos 7-12 passam 5 dias por semana nas oficinas de aprendizado em algum ofício e trabalhando para o baronato.
3. Meninos dos 12 -14 Servem na milícia 5 dias por semana.
4. Meninas dos 12 - 14 Servem nas oficinas 5 dias por semana.

**Comment by Boifuba** [comment]
Tem alguma referência de texto sobre isso?

**Comment by lincolnkerber** [comment]
2. Eles não são servos também? Imagino que possamos acordar com eles alguma forma de cooperação, ele ensina o ofício e trabalha diretamente com o senhor, montamos uma oficina pra ele em baixo da nossa asa, ele nao precisa ficar administrando o apprenticeship como um todo, só a tutelagem.
3. Dei uma pesquisada e a idade normal era 15 anos, acho que a partir disso fica dentro do contexto. (agora nao consigo entrar na mesa, vou olhar la asssim que puder)
4. Penso que as meninas da pra por pra trabalhar com as mulheres, fazendo ofícios de mulheres pra época. (principalmente a tecelagem). A ideia é que essa gente trabalhando gere o suficiente pra manter as oficinas funcionando e mais um excedente/lucro.
https://www.britannica.com/topic/history-of-work-organization-648000/The-craft-guilds
https://en.wikipedia.org/wiki/Conscription#Medieval_levies

**Comment by Boifuba** [comment]
Só uma nota. A expressão "Medieval" compreende uma extensão de tempo muito grande. A gente tá na BAIXA IDADE MÉDIA no período feudal.

**Comment by lincolnkerber** [comment]
Se aprovado por todos proponho começar estabelecendo seis"hubs" iniciais que não demandam de muita complexidade.
- Rebanho - Organização do rebanho de ovelhas
- Agricultura - Plantio e moagem de grãos, cultivo de frutas e verduras
- Silvicultura - Criação de campos de lenhadores
- Cestaria - Coleta de fibras e produção de utensílios a seren usados pelos outros hubs
- Tecelagem - Tosqueio e fabricação de roupas e tecidos.
- Construção - Inicialmente focado na melhoria/ampliação dos locais de armazenamento, silos, galpões, oficinas e casas comunais.

Em termos de mecanica da roda, o que seria este tipo de ação e qual seria potencialmente o resultado @Boifuba?

**Comment by Boifuba** [comment]
A roda é uma timeline de ações que vc determina que seus súditos/companheiros/grogues executem. Toda ação determinada requer um tempo para que fique pronta. A primeira quest da roda foi _**Criar uma Milícia**_. Quando as ordens forem dadas, a gente coloca essa ação na roda.  Foquem apenas nas quests de roda que aparecem por enquanto.
