### ISSUE TITLE
Milicia

### ISSUE THREAD

**Issue by lincolnkerber** [Boifuba/Ars-Magica#13]
Aidan, Sir Malcolm e o Bardo, vão sair pela província visitando casas e comunidades fazendo um censo e anunciando o alistamento compulsório, quem estiver na idade é convocado imediatamente.

- Toda família e indivíduo da província deve se apresentar para o recenseamento nos próximos 60 dias, todo nascimento/batismo deve ser registrado e reportado;
- Pessoas, famílias, nascimentos e batismos não registrados/recenseados incorrerão em multa aos culpados;
- Tendo efeito imediato, todo homem entre 15 e 21 serve por um ano podendo ser estendido de acordo com a necessidade;
- Todo homem completando 15 anos deve se apresentar para alistamento;
- Aquele que fugir do alistamento pagará três meses de prisão antes de iniciar o período de alistamento compulsório, a reincidência dobra a punição inicial;
- Interessados podem se oferecer para recrutamento.
- Recrutas trabalham 2 dias nas terras comunais para viabilizar a produção da "ração"
- Recrutas são divididos em 2 grupos, um serve como guarda integralmente e o outro trabalha com infraestrutura de defesa (construção e manutenção) alternando com dias de guarda.

Busco a aprovação do conselho para proceder desta maneira.

**Comment by Boifuba** [comment]
1. Não atender o chamado do fyrd é sentença de morte e perda de terras e a família é expulsa.
2. Recrutas já trabalham nas terras comunais para tirar seus sustento, TODOS trabalham nas terras comunais. 
3. Não existe hierarquia no exército para plebeus. Ou vc luta ou não.


Estamos na BAIXA IDADE MÉDIA uns 300 anos para ela acabar ainda.

**Comment by lincolnkerber** [comment]
entendi os 2 primeiros mas o terceiro não é hierarquia que estou propondo, é apenas a alocação, o rank é o mesmo.

**Comment by Boifuba** [comment]
Entendi, se ninguém tiver nada acrescentar vai pra roda.

**Comment by Villager2240** [comment]
Antonius de Jerbiton dá sua seu voto de aprovação ao censo e ao alistamento compulsório proposto.
