### ISSUE TITLE
Conserto de Ficha - Lucas

### ISSUE THREAD

**Issue by Boifuba** [Boifuba/Ars-Magica#29]
- [x] Não tem Parma Mágica
- [x] Não tem Insígnia
- [x] Forma está com os valores errados.
- [x] Lady Rank ??? RANK = STATUS
- [x]  Deletar todas as artes das Skills
- [x] Enviar as fichas pra mim

**Comment by SrPersonna** [comment]
Como eu coloco a Parma?
Como eu coloco a Insingia?
Quais são os valores certos da Forma
Porque Deletar as artes das skills?

**Comment by Boifuba** [comment]
- Parma Mágica 10 por ponto
- Dizer sem tem cheiro, cor, brilha etc.
- 5 pontos por cada ponto
- Pq isso não tem uso
